### ISSUE TITLE
Name servers weren't deployed within differenct AZ

### ISSUE THREAD

**Issue by Hao-www** [aws-samples/apache-rocketmq-on-aws#2]
[Problem Description]
No matter we use the template of existing VPC or new VPC, the name servers were deployed in the same AZ in China region. 

Use the new VPC version as example. When creating name server, the corresponding stack always use the same subnet PrimaryNodeSubnet(PrivateSubnet1A) to launch   RocketMQNameServerNode and PrimaryRocketMQBrokerNode.

[Action Required]
The result doesn't fit with the architecture the solution claimed. Please help to fix it.

```
rocketmq-entrypoint-new-vpc.template.yaml

RocketMQStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/rocketmq.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      Parameters:
        QSS3BucketName: !Ref 'QSS3BucketName'
        QSS3KeyPrefix: !Ref 'QSS3KeyPrefix'
        QSS3BucketRegion: !Ref 'QSS3BucketRegion'
        BastionSecurityGroupID: !GetAtt 'BastionStack.Outputs.BastionSecurityGroupID'
        NameServerClusterCount: !Ref 'NameServerClusterCount'
        BrokerClusterCount: !Ref 'BrokerClusterCount'
        FlushDiskType: !Ref 'FlushDiskType'
        Iops: !Ref 'Iops'
        KeyPairName: !Ref 'KeyPairName'
        NameServerInstanceType: !Ref 'NameServerInstanceType'
        RocketMQVersion: !Ref 'RocketMQVersion'
        BrokerNodeInstanceType: !Ref 'BrokerNodeInstanceType'
        PrimaryNodeSubnet: !GetAtt 'VPCStack.Outputs.PrivateSubnet1AID'
        Secondary0NodeSubnet: !GetAtt 'VPCStack.Outputs.PrivateSubnet2AID'
        Secondary1NodeSubnet: !If
          - RepeatSubnet
          - !GetAtt 'VPCStack.Outputs.PrivateSubnet2AID'
          - !GetAtt 'VPCStack.Outputs.PrivateSubnet3AID'
        VPC: !GetAtt 'VPCStack.Outputs.VPCID'
        VolumeSize: !Ref 'VolumeSize'
        VolumeType: !Ref 'VolumeType'
```

```
rocketmq.template.yaml

https://github.com/guming3d/quickstart-apache-rocketmq/blob/main/templates/rocketmq.template.yaml#L534
RocketMQNameServerNode0:
    Type: AWS::CloudFormation::Stack
    Condition: Launch1NameServer
      Parameters:
        NodeSubnet: !Ref 'PrimaryNodeSubnet'

        
 https://github.com/guming3d/quickstart-apache-rocketmq/blob/main/templates/rocketmq.template.yaml#L580       
  RocketMQNameServerNode1:
    Type: AWS::CloudFormation::Stack
    Condition: Launch2NameServer
      Parameters:
        NodeSubnet: !Ref 'PrimaryNodeSubnet'

https://github.com/guming3d/quickstart-apache-rocketmq/blob/main/templates/rocketmq.template.yaml#L663
  PrimaryRocketMQBrokerNode0:
    Type: AWS::CloudFormation::Stack
    DependsOn: RocketMQNameServerNode0
      Parameters:
        NodeSubnet: !Ref 'PrimaryNodeSubnet'

```
